FROM node:23-alpine

WORKDIR /app

# Add nodemon for development
RUN npm install -g nodemon
RUN apk add openssl3

# Only copy package files initially
COPY package*.json ./
COPY prisma ./prisma/
COPY .env .env

RUN npm install
RUN npx prisma generate

# No need to copy all files here since we're using volumes
# No need to build since we're running in dev mode

EXPOSE 3000 5555 3306

COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

CMD ["docker-entrypoint.sh"]