import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./emails/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [
    require("daisyui"),
    require("@tailwindcss/typography"),
    require("tailwindcss/plugin"),
  ],
  daisyui: {
    themes: [
      {
        "rmu": {
          ...require("daisyui/src/theming/themes")["light"],
          primary: "#013120",
          secondary: "#016936",
          "base-200": "#e6e7d8",
          accent: "#9D9B63",
        },
        "ocean": {
          ...require("daisyui/src/theming/themes")["winter"],
          primary: "#2980b9",
          "primary-content": "#ffffff",
          secondary: "#36b6ff",
          "base-200": "#ebf5f7",
          accent: "#191654",
          "accent-content": "#ffffff",
          "neutral": "#191654",
        },
        "codeCircle": {
          ...require("daisyui/src/theming/themes")["winter"],
          primary: "#014aad",
          "primary-content": "#ffffff",
          secondary: "#77e0f2",
        },
        "ncec": {
          ...require("daisyui/src/theming/themes")["corporate"],
          "primary": "#191654",
          "primary-content": "#f2f2f2",
          "secondary": "#43c6ac",
          "accent": "#43c6ac",
          "neutral": "#04313d",
          "base-100": "#ffffff",
          "base-200": "#f7f7f7",
          "info": "#006ee6",
          "success": "#00be35",
          "warning": "#a66100",
          "error": "#d90010",
        },
        parley: {
          "color-scheme": "light",
          "primary": "#000000",
          "primary-content": "oklch(100% 0 0)",
          "secondary": "#0904FF",
          "secondary-content": "oklch(100% 0 0)",
          "accent": "#00AADD",
          "accent-content": "oklch(100% 0 0)",
          "neutral": "#727272",
          "neutral-content": "oklch(100% 0 0)",
          "base-100": "oklch(100% 0 0)",
          "base-200": "oklch(0.985 0.001 106.423)",
          "base-300": "oklch(0.923 0.003 48.717)",
          "base-content": "#000000",
          "info": "oklch(79.54% 0.103 205.9)",
          "success": "oklch(90.13% 0.153 164.14)",
          "warning": "oklch(88.37% 0.135 79.94)",
          "error": "oklch(78.66% 0.15 28.47)",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0.125rem",
          "--rounded-badge": "0.125rem",
          "--tab-radius": "0.125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      "emerald",
    ],
  },
};
export default config;
